
:icons: font
:src: ../../
:srcprefix: 00-Node
:showsrc:
:github:
//:content:
:node1: vm-1234
:node2: vm-4567
:role: schedule

:checkedbox: pass:normal[{startsb}&#10004;{endsb}]

TIP: *_Time to complete 15ms_*

== Node labels

In this exercise, we shall look at setting labels to a K8s node. It can be done in multiple ways. We shall look at the following options,

[options="interactive"]
* [x] kubecl cli
* [x] K8s manifest
* [ ] API

=== Add labels
.List the nodes in your cluster
[source,go-cli]
kubectl get nodes -o wide

NOTE: You will get an output similar to this based on the cluster size,
[source,subs="verbatim,attributes"]
NAME       STATUS    ROLES     AGE       VERSION
{node1}    Ready     <none>    35h       v1.12.4
{node2}    Ready     <none>    35h       v1.12.4

.Choose one of the nodes and add a label to it
[source,kubectl,subs="verbatim,attributes"]
kubectl label nodes {node1} role={role}


.Same can be done by running the below file
====
{checkedbox} *sh {srcprefix}/_1.apply.sh*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/_1.apply.sh[]
endif::showsrc+github[]

ifdef::showsrc+content[]
[source,yaml]
----
include::{src}/{srcprefix}/01.Node-label.yaml[]
----
endif::showsrc+content[]
====


.Verify that your chosen node as role={role} label applied
[source]
kubectl get nodes --show-labels

NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
NAME       STATUS    ROLES     AGE       VERSION   LABELS
{node1}    Ready     <none>    36h       v1.12.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=minikube,role={role}

=== Clean-up
.Run the below script to undo the changes
====
{checkedbox} sh {srcprefix}/_1.clean.sh

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/_1.clean.sh[]
endif::showsrc+github[]
====

