:icons: font
:src: ../../
:srcprefix: 01-Pod
:appname: spring-music
:showsrc:
:github:
//:content:
:role: schedule

TIP: *_Time to complete 30ms_*

A pod is the atom of K8s. It is the fundamental unit of deployment with a group of one or more containers (such as Docker containers), with shared storage/network, and a specification for how to run the containers.

In this exercise, we shall cover the following operations using K8s manifests,


[options="interactive"]
* [x] Creating a _Pod_
* [x] _cgroup_ resources and limits
* [x] _Healthcheck_
* [x] _Lifecycle_ hooks
* [x] _Pod:Node_ association

NOTE: Will install all the objects to the _default_ namespace.

== Pod
=== Create an atom
.List the pods in the default namespace
[source,go-cli]
kubectl get pods

NOTE: The output will be similar to this,
[source]
No resources found.


.Create a new Pod by running the below file
====
{checkedbox} *kubectl apply -f  {srcprefix}/01.Pod.yaml*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/01.Pod.yaml[]
endif::showsrc+github[]
====

.Verify that a pod named {appname} gets created
[source]
kubectl get pods

NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
NAME           READY     STATUS    RESTARTS   AGE
{appname}      1/1       Running   0          11s


==== Clean-up
.Run the below script to undo the changes
====
{checkedbox} sh {srcprefix}/_1.clean.sh

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/_1.clean.sh[]
endif::showsrc+github[]
====

TIP: Unlike other manifests, only a limited fields of _Pod_ spec can be overridden. Hence it is recommended to clean-up resources before moving to the next example.


=== Assign Resources requests & limits

NOTE: CPU and memory are each a resource type. A resource type has a base unit. CPU is specified in units of cores, and memory is specified in units of bytes. CPU and memory are collectively referred to as compute resources, or just resources. Compute resources are measurable quantities that can be requested, allocated, and consumed.


.Create a new pod by running the below file
====
{checkedbox} *kubectl apply -f  {srcprefix}/02.Pod-resource-limit.yaml*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/02.Pod-resource-limit.yaml[]
endif::showsrc+github[]
====

.Verify that a pod named {appname} gets created
[source,subs="verbatim,attributes"]
kubectl get pods/{appname} -o custom-columns=NAME:.metadata.name,STATUS:.status.phase,CPU_REQUEST:spec.containers[*].resources.requests.cpu,CPU_LIMITT:.spec.containers[*].resources.limits.cpu,MEM_REQUEST:spec.containers[*].resources.requests.memory,MEM_LIMITT:.spec.containers[*].resources.limits.memory


NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
NAME           STATUS    CPU_REQUEST   CPU_LIMITT   MEM_REQUEST   MEM_LIMITT
{appname}      Running   250m          750m         768M          1G

TIP: Although requests and limits can only be specified on individual Containers, a Pod resource request/limit for a particular resource type is the sum of the resource requests/limits of that type for each Container in the Pod

==== Clean-up
.Run the below script to undo the changes
====
{checkedbox} sh {srcprefix}/_1.clean.sh

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/_1.clean.sh[]
endif::showsrc+github[]
====

TIP: Unlike other manifests, only a limited fields of _Pod_ spec can be overridden. Hence it is recommended to clean-up resources before moving to the next example.


=== Health Check

[NOTE]
====
*_Liveness probe_* is used by Kubelet to know when to restart a Container. For example, liveness probes could catch a deadlock, where an application is running, but unable to make progress. Restarting a Container in such a state can help to make the application more available despite bugs.

*_Readiness probe_* is used by Kubelete to know when a Container is ready to start accepting traffic.
====

.Create a new pod by running the below file
====
{checkedbox} *kubectl apply -f  {srcprefix}/03.Pod-health-check.yaml*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/03.Pod-health-check.yaml[]
endif::showsrc+github[]
====

.Verify that a pod named {appname} gets created
[source,subs="verbatim,attributes"]
kubectl get pods/{appname} -o custom-columns=NAME:.metadata.name,STATUS:.status.phase,READINESS_PROBE:.spec.containers[*].readinessProbe.httpGet.path,LIVENESS_PROBE:.spec.containers[*].livenessProbe.httpGet.path


NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
NAME           STATUS    READINESS_PROBE    LIVENESS_PROBE
{appname}      Running   /actuator/health   /actuator/health

TIP: A Pod is considered ready when all of its Containers are ready. One use of this signal is to control which Pods are used as backends for Services. When a Pod is not ready, it is removed from Service load balancers.

==== Clean-up
.Run the below script to undo the changes
====
{checkedbox} sh {srcprefix}/_1.clean.sh

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/_1.clean.sh[]
endif::showsrc+github[]
====

TIP: Unlike other manifests, only a limited fields of _Pod_ spec can be overridden. Hence it is recommended to clean-up resources before moving to the next example.


=== Lifecycle Hooks

[NOTE]
====
There are two hooks that are exposed to Containers:

* *_PostStart_* executes immediately after a container is created. However, there is no guarantee that the hook will execute before the container ENTRYPOINT. No parameters are passed to the handler.

* *_PreStop_* is called immediately before a container is terminated. It is blocking, meaning it is synchronous, so it must complete before the call to delete the container can be sent. No parameters are passed to the handler
====

.Create a new pod by running the below file
====
{checkedbox} *kubectl apply -f  {srcprefix}/04.Pod-lifecycle-hook.yaml*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/04.Pod-lifecycle-hook.yaml[]
endif::showsrc+github[]
====

.Verify that a pod named {appname} gets created
[source,subs="verbatim,attributes"]
kubectl get pods/{appname}


NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
NAME           READY     STATUS    RESTARTS   AGE
{appname}      1/1       Running   0          11s

.ssh to the container to look into the content of /usr/share/message file to verify that the _postStart_ script got executed

[source,subs="verbatim,attributes"]
----
kubectl exec -it {appname} -- /bin/sh

more /usr/share/message
----

IMPORTANT: The output will be similar to this
[source]
Hello Spring K8s folks

==== Clean-up
.Run the below script to undo the changes
====
{checkedbox} sh {srcprefix}/_1.clean.sh

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/_1.clean.sh[]
endif::showsrc+github[]
====

TIP: Unlike other manifests, only a limited fields of _Pod_ spec can be overridden. Hence it is recommended to clean-up resources before moving to the next example.


=== Pod Node binding

[NOTE]
====
You can constrain a pod to only be able to run on particular nodes or to prefer to run on particular nodes. There are several ways to do this, and will look at how to use label selectors to make the selection
====

.Create a new pod by running the below file
====
{checkedbox} *kubectl apply -f {srcprefix}/05.Pod-node-selector.yaml*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/05.Pod-node-selector.yaml[]
endif::showsrc+github[]
====

.Verify the output of the command
[source,subs="verbatim,attributes"]
kubectl get pods/{appname}


WARNING: The output will be similar to this
[source,subs="verbatim,attributes"]
NAME           READY     STATUS    RESTARTS   AGE
{appname}      0/1       Pending   0          4s

Status of the pod would be pending as we have tried to assign it to a node with label having key as _role_ and value as _{role}_, but none of the nodes will have the label. Refer <<Add labels>> section to assign the required label.


NOTE: The output will be similar to this. Now the pod schedule should have happened to the node with label having key as _role_ and value as _{role}_
[source,subs="verbatim,attributes"]
NAME           READY     STATUS    RESTARTS   AGE
{appname}      1/1       Running   0          11s

==== Clean-up
.Run the below script to undo the changes
====
{checkedbox} *sh {srcprefix}/_1.clean.sh*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/_1.clean.sh[]
endif::showsrc+github[]
====

TIP: If you delete a pod, it won't get created automatically.
