:icons: font
:src: ../../
:srcprefix: 03-Node-Pod
:appname: spring-music
:showsrc:
:github:
//:content:
:role: schedule

TIP: *_Time to complete 30ms_*

Node affinity, is a property of pods that attracts them to a set of nodes (either as a preference or a hard requirement). Taints are the opposite – they allow a node to repel a set of pods.

Taints and tolerations work together to ensure that pods are not scheduled onto inappropriate nodes. One or more taints are applied to a node; this marks that the node should not accept any pods that do not tolerate the taints. Tolerations are applied to pods, and allow (but do not require) the pods to schedule onto nodes with matching taints

In this exercise, we shall cover the following operations using K8s manifests,

[options="interactive"]
* [x] _Tolerating_ a Node _Taint_
* [x] _Un-tolerating_ a Node _Taint_
* [x] _Runtime Node _Taint_

NOTE: Will install all the objects to the _default_ namespace.

== Taint and Tolerations

=== Tolerate a Taint

.List the replicasets in the default namespace
[source,go-cli]
kubectl get rs

NOTE: The output will be similar to this,
[source]
No resources found.


.Create the node and pod objects by running the below file
====
{checkedbox} *sh {srcprefix}/01_.apply.sh*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/01_.apply.sh[]
endif::showsrc+github[]
====


NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
----
kubectl get nodes -o yaml -o jsonpath={".items[*].spec.taints}"

[map[effect:NoSchedule key:dedicated value:host]]

kubectl get pods -o yaml -o jsonpath={".items[*].spec.tolerations}"

[map[effect:NoSchedule key:dedicated operator:Equal value:host]
----

NOTE: It places a _taint_ on the chosen node with key as dedicated, value as host, and taint effect NoSchedule. This means that no pod will be able to schedule onto the node unless it has a matching toleration. To schedule a pod onto the node we have to have matching _toleration_ in the PodSpec

==== Clean-up
.Run the below script to undo the changes
====
{checkedbox} sh {srcprefix}/_1.clean.sh

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/01_.clean.sh[]
endif::showsrc+github[]
====


=== Un-tolerate a Taint

.List the replicasets in the default namespace
[source,go-cli]
kubectl get rs

NOTE: The output will be similar to this,
[source]
No resources found.


.Create the node and pod objects by running the below file
====
{checkedbox} *sh {srcprefix}/02_.apply.sh*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/02_.apply.sh[]
endif::showsrc+github[]
====


NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
----
kubectl get nodes -o yaml -o jsonpath={".items[*].spec.taints}"

[map[effect:NoSchedule key:dedicated value:host]]

kubectl get pods -o yaml -o jsonpath={".items[*].spec.tolerations}"

[map[]]

kubectl get rs,pods
NAME                                 DESIRED   CURRENT   READY     AGE
replicaset.extensions/{appname}      1         1         0         20s

NAME                     READY     STATUS    RESTARTS   AGE
pod/{appname}-vbbkl      0/1       Pending   0          20s
----

NOTE: Pod will be in pending state as it can't tolerate the taint

==== Clean-up
.Run the below script to undo the changes
====
{checkedbox} sh {srcprefix}/_1.clean.sh

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/02_.clean.sh[]
endif::showsrc+github[]
====


=== Runtime Taint

.List the replicasets in the default namespace
[source,go-cli]
kubectl get rs

NOTE: The output will be similar to this,
[source]
No resources found.


.Create the node and pod objects by running the below file
====
{checkedbox} *sh {srcprefix}/03_.Node-taint-match-no-match-apply.sh*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/03_.Node-taint-match-no-match-apply.sh[]
endif::showsrc+github[]
====


NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
----

watch kubectl get pods
Every 2.0s: kubectl get pods                                                                                                                                                                           sv.local: Sun Feb 10 16:05:03 2019

NAME                 READY     STATUS    RESTARTS   AGE
spring-music-6mdvd   1/1       Running   0          11s

NAME                 READY     STATUS    RESTARTS   AGE
spring-music-w72zv   0/1       Pending   0          42s
----

NOTE: It places a _taint_ on the chosen node with key as dedicated, value as host, and taint effect NoSchedule. This means that no pod will be able to schedule onto the node unless it has a matching toleration. As the pod has a matching _toleration_ it would get scheduled on the node and hence the status was initially Running. After few seconds, it would get updated to Pending as the addition of a new Runtime _NoExecute_ operator would make the pod un-tolerate the taint.

==== Clean-up
.Run the below script to undo the changes
====
{checkedbox} sh {srcprefix}/03_.clean.sh

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/_1.clean.sh[]
endif::showsrc+github[]
====
