:icons: font
:src: ../../
:srcprefix: 04-Deployment
:appname: spring-music
:showsrc:
:github:
//:content:
:role: schedule

TIP: *_Time to complete 30ms_*

A Deployment controller provides declarative updates for Pods and ReplicaSets.

You describe a desired state in a Deployment object, and the Deployment controller changes the actual state to the desired state at a controlled rate. You can define Deployments to create new ReplicaSets, or to remove existing Deployments and adopt all their resources with new Deployments.

In this exercise, we shall cover the following operations using K8s manifests,

[options="interactive"]
* [x] _Create_ a _Deployment_
* [x] Deployment _Update Strategies_

NOTE: Will install all the objects to the _default_ namespace.

== Deployment
=== Create a Deployment

.List the deployments in the default namespace
[source,go-cli]
kubectl get deploy

NOTE: The output will be similar to this,
[source]
No resources found.


.Create a Deployment object by running the below file
====
{checkedbox} *kubectl apply -f {srcprefix}/01.Deployment.yaml*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/01.Deployment.yaml[]
endif::showsrc+github[]
====

.Verify the output
[source]
kubectl get deploy,rs,pods


NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
----
NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/{appname}      2         2         2            0           2m16s

NAME                                           DESIRED   CURRENT   READY     AGE
replicaset.extensions/{appname}-846f7447f      2         2         0         2m16s

NAME                               READY     STATUS    RESTARTS   AGE
pod/{appname}-846f7447f-znb58      1/1       Running   1          2m16s
pod/{appname}-846f7447f-zqfs2      1/1       Running   1          2m16s
----

NOTE: No need to run the clean-up script for this example.


=== Update a Deployment

==== Recreate

.List the deployments in the default namespace
[source,go-cli]
kubectl get deploy,rs,pods

NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
----
NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/{appname}      2         2         2            0           2m16s

NAME                                           DESIRED   CURRENT   READY     AGE
replicaset.extensions/{appname}-846f7447f      2         2         0         2m16s

NAME                               READY     STATUS    RESTARTS   AGE
pod/{appname}-846f7447f-znb58      1/1       Running   1          2m16s
pod/{appname}-846f7447f-zqfs2      1/1       Running   1          2m16s
----

.Watch the deployment in a new window
[source,go-cli]
kubectl get deploy,rs,pods

NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
----
NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/{appname}      2         2         2            0           2m16s

NAME                                           DESIRED   CURRENT   READY     AGE
replicaset.extensions/{appname}-846f7447f      2         2         0         2m16s

NAME                               READY     STATUS    RESTARTS   AGE
pod/{appname}-846f7447f-znb58      1/1       Running   1          2m16s
pod/{appname}-846f7447f-zqfs2      1/1       Running   1          2m16s
----

.Update the Deployment object by running the below file
====
{checkedbox} *kubectl apply -f {srcprefix}/02.Deployment-recreate.yaml*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/02.Deployment-recreate.yaml[]
endif::showsrc+github[]
====


NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
----
NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/{appname}      2         0         0            0           9m13s

NAME                                           DESIRED   CURRENT   READY     AGE
replicaset.extensions/{appname}-846f7447f      0         0         0         9m13s

NAME                               READY     STATUS        RESTARTS   AGE
pod/{appname}-846f7447f-znb58      0/1       Terminating   0          9m13s
pod/{appname}-846f7447f-zqfs2      0/1       Terminating   0          9m13s
----

TIP: All existing Pods are killed before new ones are created when _.spec.strategy.type==Recreate_ and it doesn't guarantee zero down time deployment

===== Clean-up
.Run the below script to undo the changes
====
{checkedbox} sh {srcprefix}/02_.clean.sh

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/02_.clean.sh[]
endif::showsrc+github[]
====


==== RollingUpdate

.Create a Deployment object by running the below file
====
{checkedbox} *kubectl apply -f {srcprefix}/03.Deployment.yaml*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/03.Deployment.yaml[]
endif::showsrc+github[]
====

.List the deployments in the default namespace
[source,go-cli]
kubectl get deploy,rs,pods

NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
----
NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/{appname}      2         2         2            0           2m16s

NAME                                           DESIRED   CURRENT   READY     AGE
replicaset.extensions/{appname}-846f7447f      2         2         0         2m16s

NAME                               READY     STATUS    RESTARTS   AGE
pod/{appname}-846f7447f-znb58      1/1       Running   1          2m16s
pod/{appname}-846f7447f-zqfs2      1/1       Running   1          2m16s
----

.Watch the deployment in a new window
[source,go-cli]
kubectl get deploy,rs,pods

NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
----
NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/{appname}      2         2         2            0           2m16s

NAME                                           DESIRED   CURRENT   READY     AGE
replicaset.extensions/{appname}-846f7447f      2         2         0         2m16s

NAME                               READY     STATUS    RESTARTS   AGE
pod/{appname}-846f7447f-znb58      1/1       Running   1          2m16s
pod/{appname}-846f7447f-zqfs2      1/1       Running   1          2m16s
----

.Update the Deployment object by running the below file
====
{checkedbox} *kubectl apply -f {srcprefix}/03.Deployment-rolling-update.yaml*

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/03.Deployment-rolling-update.yaml[]
endif::showsrc+github[]
====


NOTE: The output will be similar to this
[source,subs="verbatim,attributes"]
----
NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/{appname}      2         0         0            0           9m13s

NAME                                           DESIRED   CURRENT   READY     AGE
replicaset.extensions/{appname}-846f7447f      0         0         0         9m13s

NAME                               READY     STATUS        RESTARTS   AGE
pod/{appname}-846f7447f-znb58      0/1       Terminating   0          9m13s
pod/{appname}-846f7447f-zqfs2      0/1       Running       0          9m13s
pod/{appname}-846f7447f-78lwx      0/1       Running       0          22s
pod/{appname}-8677d84f54-66fgh     0/1       Running       0          4s
----

[TIP]
====
The Deployment updates Pods in a rolling update fashion when _.spec.strategy.type==RollingUpdate_. You can specify _maxUnavailable_ and _maxSurge_ to control the rolling update process

*maxUnavailable* is an optional field that specifies the maximum number of Pods that can be unavailable during the update process.

*maxSurge* is an optional field that specifies the maximum number of Pods that can be created over the desired number of Pods.
====

===== Clean-up
.Run the below script to undo the changes
====
{checkedbox} sh {srcprefix}/_1.clean.sh

ifdef::showsrc+github[]
NOTE: Source:
include::https://github.com/srinivasa-vasu/k8s-workshop/blob/master/{srcprefix}/_1.clean.sh[]
endif::showsrc+github[]
====


